persistence: SensorSystemRepository: Rework method to expose SensorLocations
Simple Derived Query Method seems to be unable to handle our requirement, Switch to a Query method

Fixes:
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [...SensorSystem] to type [...SensorLocation]